<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<style type="text/css" rel="stylesheet">
#mini-cart .product-item-name>a{display: inline-block;line-height: 18px;text-transform: capitalize;color: #555;}
#mini-cart .product-item-name>a:hover{color:#4c6689;}
#mini-cart .options .content>.options{margin: 0;}
@media (min-width: 769px),print{
#mini-cart .product-item-pricing .price-container,
#mini-cart .product-item-pricing .details-qty{display:inline-block;vertical-align: middle;}
#mini-cart .product-item-pricing .details-qty{margin: 0;}
.minicart-items .product-item-pricing .label{width:auto;margin: 0 2px 0 10px;}
.block-minicart .subtotal .price{font-size:24px;}
}
</style>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
	   <span class="cart-icon icons">
			<span class="text"><i class="flaticon-cart"></i></span>
			<span class="text-cart"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
			<span class="counter qty empty"
				  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
				<span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
				<span class="counter-label">
				<!-- ko if: getCartParam('summary_count') -->
					<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
					<!-- ko i18n: 'items' --><!-- /ko -->
				<!-- /ko -->
				</span>
			</span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


