<style xml="space">
	.h4blue {
		color: #4c6689;
		margin-top: 40px;
	}

	#wholesale-form .fieldset>.field,
	.fieldset>#wholesale-form .fields>.field {
		margin: 0 0 5px;
	}

	@media(min-width: 769px),
	print {
		#wholesale-form {
			min-width: 600px;
			width: 50%;
			margin: 60px 0 0 0;
		}
		#wholesale-form input[type='text']:focus,
		#wholesale-form input[type='email']:focus,
		#wholesale-form input[type='number']:focus,
		#wholesale-form select:focus {
			border-color: #68a8e0;
		}
		#wholesale-form .fieldset>.field>.label,
		#wholesale-form .fieldset>.fields>.field>.label {
			margin: 0 0 4px;
		}
		.field.col-2 {
			display: inline-block;
			width: 48%;
		}
		.field.col-r {
			float: right;
		}
		.fieldset.company {
			margin: 0 0 10px;
		}
		.field.col-2.additonal {
			width: 30%;
		}
		.field.col-2.additionalname {
			width: 66%;
		}
		.field.file .small {
			border-top: 1px solid #ccc;
		}
		#additionalCategory {
			height: 40px;
		}
		#file {
			display: inline-block;
		}
	}
</style>
<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>
<div class="breadcrumbs" style="padding-left:0;">
	<ul class="items">
		<li class="item home">
			<a href="<?php echo $storeManager->getStore()->getBaseUrl();?>" title="Go to Home Page"> Home </a>
		</li>
		<li class="item cms_page">
			<strong>Dropshipping and Wholesale</strong>
		</li>
	</ul>
</div>
<h3 style="color: #4c6689;">Become Wholesale or dropshipping Parnter</h3>
<h4 class="h4blue">About Upettools</h4>
<p>Upettools is a global supplier of professional aquarium equipment that provides box&amp; water brand products which contains
	Aquariums &amp; Tanks, Aquarium Pump, Aquarium Thermometers, Aquarium Air Pumps etc. Upettools is committed to providing
	the most professional products, the most appropriate price and the most rigorous quality test and the best shopping experience
	for the global aquarium and ornamental fish lovers !</p>
<h4 class="h4blue">Products</h4>
<p>We supply:</p>
<ul>
	<li>
		<a href="/fish-aquatic/aquarium-filter.html">Aquarium Filter</a>
	</li>
	<li>
		<a href="/fish-aquatic/aquarium-lights.html">Aquarium Lights</a>
	</li>
	<li>
		<a href="/fish-aquatic/air-pumps-accessories.html">Air Pumps &amp; Accessories
		</a>
	</li>
	<li>
		<a href="/fish-aquatic/aquariums-tanks-cleaning-tools.html">Cleaning Tools</a>
	</li>
	<li>
		<a href="/fish-aquatic/aquarium-device.html">Aquarium Devices</a>
	</li>
	<li>
		<a href="/fish-aquatic/aquariums-tanks-temperature-control-products.html">Temperature Control Products</a>
	</li>
	<li>
		<a href="/fish-aquatic/aquarium-water-treatment.html">Aquarium Water Treatment</a>
	</li>
</ul>
<h4 class="h4blue">Enjoy The Discount</h4>
<p>After becoming our business partner, you will enjoy a lot of benefits.</p>
<p>We can offer more favorable prices, faster shipping and newer products.</p>
<p>We can also customize different products, such as size, color, power or with other functions.</p>
<h4 class="h4blue">Contact Us</h4>
<p>Upettools is very interested in working with new distribution partners.</p>
<p>If your company is interested in the distribution of our products, please send email to
	<a style="color: #4c6689;" href="mailto:info@upettools.com">info@upettools.com</a>or fill out the contact form below.</p>
<form id="wholesale-form" action="/wholesale" method="post">
	<fieldset class="fieldset personal">
		<legend class="legend">
			<span>Personal Information</span>
		</legend>
		<div class="field col-2 field-name-firstname required">
			<label class="label" for="firstname">
				<span>First Name</span>
			</label>
			<div class="control">
				<input id="firstname" class="input-text required-entry" title="First Name" autocomplete="off" name="firstname" type="text"
				    value="" data-validate="{required:true}" />
			</div>
		</div>
		<div class="field col-2 col-r field-name-lastname required">
			<label class="label" for="lastname">
				<span>Last Name</span>
			</label>
			<div class="control">
				<input id="lastname" class="input-text required-entry" title="Last Name" autocomplete="off" name="lastname" type="text" value=""
				    data-validate="{required:true}" />
			</div>
		</div>
		<div class="field col-2 field-eamil required">
			<label class="label" for="email">
				<span>Email</span>
			</label>
			<div class="control">
				<input id="email" class="input-text required-entry" title="email" autocomplete="off" name="email" type="email" value="" data-validate="{required:true}"
				/>
			</div>
		</div>
		<div class="field col-2 col-r telephone required">
			<label class="label" for="telephone">
				<span>Phone Number</span>
			</label>
			<div class="control">
				<input id="telephone" class="input-text  required-entry" title="Phone Number" autocomplete="off" name="telephone" type="text"
				    value="" />
			</div>
		</div>
	</fieldset>
	<fieldset class="fieldset company">
		<legend class="legend">
			<span>Additonal Information</span>
		</legend>
		<div class="field col-2 additonal">
			<label class="label" for="additionalCategory">
				<span>Organization</span>
			</label>
			<div class="control">
				<select name="additionalcategory" id="additionalCategory">
					<option value="0">Please Choose</option>
					<option value="1">Aqua Company</option>
					<option value="2">Aquarium</option>
					<option value="3">Dropshipping</option>
				</select>
			</div>
		</div>
		<div class="field col-2 col-r additionalname">
			<label class="label" for="additionalname">
				<span>Additional Name</span>
			</label>
			<div class="control">
				<input id="additionalname" class="input-text" title="Additional Name" autocomplete="off" name="additionalname" type="text"
				    value="" />
			</div>
		</div>
		<div class="field sales-amount required">
			<label class="label" for="sales-amount">
				<span>Sales target amount</span>
			</label>
			<div class="control">
				<input id="sales-amount" class="input-text required-entry" title="sales-amount" autocomplete="off" name="sales-amount" type="number"
				    value="" />
			</div>
		</div>
		<div class="field sales-area required">
			<label class="label" for="sales-area">
				<span>Sales to where</span>
			</label>
			<div class="control">
				<input id="sales-area" class="input-text required-entry" title="sales-area" autocomplete="off" name="sales-area" type="text"
				    value="" />
			</div>
		</div>
		<div class="field interested-categories required">
			<label class="label" for="interested-categories">
				<span>Interested categories</span>
			</label>
			<div class="control">
				<input id="interested-categories" class="input-text required-entry" title="interested-categories" autocomplete="off" name="interested-categories"
				    type="text" value="" />
			</div>
		</div>
		<div class="field file">
			<label class="label" for="file">
				<span>Upload file</span>
			</label>
			<p class="small">We look forward to your uploading these documents: company photos, shop pictures, or other things that allow us to better
				understand you.File format like *.rar, *.zip.File does not exceeding 5M!
			</p>
			<div class="control">
				<input id="file" title="file" autocomplete="off" name="file" type="file" value="" />
				<input id="upload" type="button" value="Upload" />
			</div>
		</div>
		<p id="upload_message"></p>
	</fieldset>
	<div class="actions-toolbar">
		<div class="primary">
			<button class="action submit primary" title="Submit" type="submit">
				<span>Submit</span>
			</button>
		</div>
	</div>
</form>
<script type="text/javascript" xml="space">
	require(['jquery', 'mage/mage'], function ($) {
			var dataForm = $('#wholesale-form');
			var ignore = null;
			dataForm.mage('validation', {
				ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
			}).find('input:text').attr('autocomplete', 'off');
			var $message = $('#upload_message');
			$('#upload').click(function () {
				if ($.ajax) {
					$.ajax({
						type: 'post',
						url: "/upfile.php",
						data: $('#file'), //数据对象
						async: true,
						processData: false, //processData 默认为false，当设置为true的时候,jquery ajax 提交的时候不会序列化 data，而是直接使用data
						contentType: false,
						beforeSend: function () {},
						complete: function () {},
						success: function (data) {},
						error: function () {
							$message.text('Failed to upload file.');
						}
					});
				}
			});
		}

	);
</script>