<?php
$footer = $this->getConfig('vicomage_general_config/footer');
$footer_type = $this->getConfig('vicomage_general_config/footer/footer_type');
?>
<div class="footer footer-type<?php echo $footer_type; ?>">
    <?php if ($footer['footer_top']) { ?>
        <div class="footer-top">
            <?php
            if ($footer['footer_top_custom']) {
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if ($block) {
                    $block->setBlockId($footer['footer_top_custom']);
                }
                if ($block) {
                    echo $block->toHtml();
                }
            }
            ?>
        </div>
    <?php } ?>

    <?php if ($footer['footer_middle']) { ?>
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <?php
                    if ($footer['footer_middle_custom']) {
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if ($block) {
                            $block->setBlockId($footer['footer_middle_custom']);
                        }
                        if ($block) {
                            echo $block->toHtml();
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if ($footer['footer_middle_2']) { ?>
        <div class="footer-middle-2">
            <div class="container">
                <div class="row">
                    <?php
                    if ($footer['footer_middle_2_custom']) {
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if ($block) {
                            $block->setBlockId($footer['footer_middle_2_custom']);
                        }
                        if ($block) {
                            echo $block->toHtml();
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if ($footer['footer_bottom']) { ?>
        <?php if ($footer_type == 2 || $footer_type == 3): ?>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-mobile-12">
                            <?php echo $this->getChildHtml("footer.copyright"); ?>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-mobile-12">
                            <?php
                            if ($footer['footer_bottom_custom']) {
                                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                                if ($block) {
                                    $block->setBlockId($footer['footer_bottom_custom']);
                                }
                                if ($block) {
                                    echo $block->toHtml();
                                }
                            }
                            ?>
                            <?php if ($footer['footer_store_switcher']) { ?>
                                <?php echo $this->getChildHtml("footer.store_switcher"); ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($footer_type == 1 || $footer_type == 4): ?>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-mobile-12">
                            <?php // echo $this->getChildHtml("footer.copyright"); ?>
                            <?php
                            if ($footer['footer_bottom_custom']) {
                                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                                if ($block) {
                                    $block->setBlockId($footer['footer_bottom_custom']);
                                }
                                if ($block) {
                                    echo $block->toHtml();
                                }
                            }
                            ?>
                            <?php if ($footer['footer_store_switcher']) { ?>
                                <?php echo $this->getChildHtml("footer.store_switcher"); ?>
                            <?php } ?>
						</div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php } ?>

</div>
<a id="backtotop" href="#top" style="display: block;" class=""><span class="fa fa-angle-up"></span></a>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function() {
            $('.mobile-collapsible .heading:gt(0)').click(function(){
                //_checkHidden();
                $(this).closest('.mobile-collapsible').find('.toggle-content').toggleClass('hidden-xs');
            });
           /*tabs at go to checkout*/
            $(document).on('click','.block-customize .tabs li',function(){
                if(!$(this).hasClass('current')){
                    $(this).addClass('current').siblings().removeClass('current');
                    if($(this).hasClass('sign')){
                        $('.block-customize .block-customer-login').removeClass('hidden-xs').siblings('.block-new-customer').addClass('hidden-xs');
                    }else if($(this).hasClass('new')){
                        $('.block-customize .block-new-customer').removeClass('hidden-xs').siblings('.block-customer-login').addClass('hidden-xs');
                    }
                }
            });
           
            function _checkHidden(){//hide all list
                $('.mobile-collapsible .toggle-content:gt(0)').each(function(){
                    if(!$(this).hasClass('hidden-xs')){
                        $(this).addClass('hidden-xs');
                    }
                });
            }
        });
        
    });
</script>
