<?php
    $header_type = $this->getConfig('vicomage_general_config/header/header_type');
?>
<!-- new add at header -->
<style type="text/css" media="all">
	/* --- common style --- */
	.toolbar select{padding-left: 10px;}
	.swatch-option{border: 1px solid rgba(0, 0, 0, 0.2);}
	.header-top .header-top-right,.page-header #switcher-currency .action.toggle:after{line-height:30px;}
	.links-header-dropdown .link.wishlist .qty>i{font-style:normal;}
	.account .page-wrapper .column.main a{color: #4c6689;}
	.account .page-wrapper .column.main a:hover{color: #2a6ac1;text-decoration: underline;}
	#switcher-language a{color: #fff;font-size: 12px;text-shadow: 0 4px 4px rgba(0,0,0,0.6);padding: 2px 4px;
		border-radius: 5px;border-width: 3px;border-style: solid;
		border-color: #e66e2e #bb4508 #b1521e #b54a11;
		background: #c34807;
		background: -webkit-linear-gradient(to bottom,#e06422,#d6530d);
		background: linear-gradient(to bottom,#e06422,#d6530d);
		-webkit-transition: all 0.1s linear;
		transition: all 0.1s linear;}
	#switcher-language a.current{
		cursor:default;
		text-decoration: none;
	}
	#switcher-language a.lang:hover{
		text-decoration: none;
		text-shadow: 0 2px 4px rgba(0,0,0,0.6);
		border-color: #ea6f2d #d25b1d #ba4000 #b54a11;
		background: -webkit-linear-gradient(to bottom,#f1702b,#da5814);
		background: linear-gradient(to bottom,#f1702b,#da5814);
	}
	#switcher-language a.lang:active{
		text-decoration: none;
		text-shadow: 0 2px 4px rgba(0,0,0,0.6);
		border-color: #da5d1a #9c3d0c #b3490f #b54a11;
		background: -webkit-linear-gradient(to bottom,#bb531b,#ec8650);
		background: linear-gradient(to bottom,#bb531b,#ec8650);
	}
	#fixedWholesale{display:none;}
	.product-item-actions .actions-primary .stock.unavailable{
	padding: 0 15px;font-weight: 700;font-size: 12px;line-height: 30px;background:#ffffff;}
	.product-item-actions .actions-primary .stock.unavailable span{text-decoration: underline;}
	#backtotop{right: 12px;background-color: #0584bb;border-radius: 4px;}
	#backtotop:hover{background:#333333;}
	.minicart-items .item-qty{width:40px;padding:0;}
	@media all and (min-width: 769px), print {
		html.ie8,.ie8 body,html.ie9,.ie9 body,html.ie10,.ie10 body,html.ie11,.ie11 body{height:auto;}/*IE hack*/
		.header-content-menu{position: relative;}
		#fixedWholesale{display:block;position:absolute;right:0;top:10px;color:#fff;font-size:14px;
			text-shadow: 0 4px 4px rgba(0,0,0,0.6);
			padding: 2px 4px;border-radius: 5px;border-width: 3px;border-style: solid;
			border-color: #0584bb #03577b #094f6d #106286;
			background: #106286;
			background: -webkit-linear-gradient(to bottom,#0584bb,#4c6689);
			background: linear-gradient(to bottom,#0584bb,#4c6689);
			-webkit-transition: all 0.1s linear;
			transition: all 0.1s linear;
		}
		#fixedWholesale:hover{
			text-decoration: none;
			border-color: #006f9e #03577b #094f6d #106286;
			background: -webkit-linear-gradient(to bottom,#07506f,#577092);
			background: linear-gradient(to bottom,#07506f,#577092);
			
		}
		#fixedWholesale:active{
			text-decoration: none;
			border-color: #1496cc #03577b #0a5777 #106286;
			background: -webkit-linear-gradient(to bottom,#0f688e,#0f80af);
			background: linear-gradient(to bottom,#0f688e,#0f80af);
		}
		.header-container-fixed #fixedWholesale{display:none;}
		#backtotop{bottom:40px;}
	}
	@media only screen and (min-width: 769px) and (max-width: 898px), print {
		.header-container-fixed #mainMenu>li:first-child{display: none;}
	}
	@media only screen and (max-width: 768px), print{
		.page-header .header-search {top: 25px;left: 60px;}
		.page-header .switcher .options ul.dropdown{left: 0;}
		.page-header.header-type1 .header-right{z-index:51;}
		.columns .column.main{padding-bottom:0;}
		#switcher-language-nav,#switcher-currency-nav {border-bottom:1px solid #d1d1d1;}
		#switcher-language-nav a{display:inline-block;font-weight:normal;}
		#switcher-language-nav a.lang{padding:5px 15px;}
		#switcher-language-nav a.lang::before {content: '\e608';font-family: 'luma-icons';-webkit-font-smoothing: antialiased;font-size: 8px;
		line-height: 20px;color: inherit;margin: 0;vertical-align: top;display: inline-block;font-weight: normal;overflow: hidden;speak: none;text-align: center;}
		#switcher-currency-nav ul.dropdown{box-shadow:none;background:none;}
		#switcher-currency-nav .options.active ul.dropdown{position:initial;}
		.page-header .switcher .options ul.dropdown li:hover{background:none;}
		.navigation .submenu > li{border-top: 1px solid #ddd;}
		.prolist-feature-top .title-page{margin:10px 0;}
		.products-grid .product-item{margin-bottom:10px;}
		.product-item-details{padding-top:0;}
		.product-item-name{margin:2px 0;}
		.product-item-name, .product.name a{font-size:12px;}
		.product-reviews-summary{margin:0;line-height:0;}
		.rating-summary .rating-result[title="0%"] {display: none;}
		.form-customer-create .actions-toolbar .secondary a.action ,
		.form-password-forget .actions-toolbar .secondary a.action{color: #fff;}
		.page-header .switcher .options .action.toggle:after{line-height:20px;}
		.product-label {top: 5px;left: 8px;}
		.vicomage-slider .slick-slide[data-slick-index="0"] .text-slide .caption1{color: #c24343;text-shadow: -1px 0px 1px #fff, 2px -1px 2px rgba(0,0,0,.8);}
		.vicomage-slider .slick-active .slide-caption .caption1{font-family: Gabriola;font-style: italic;font-weight: 700;}
		.vicomage-slider .slick-active .slide-caption .caption2,
		.vicomage-slider .slick-active .slide-caption .caption3{text-transform: capitalize;font-size: 14px;font-weight: normal;}
		#backtotop{bottom:60px;right:14px;opacity:0.8;}
		.catalog-product-view #backtotop{bottom: 114px;}
		.zopim{top:initial;bottom:0!important;opacity:0.88;}
		.catalog-product-view>.zopim{bottom: 70px!important;}
		.page-header .wishlist-header .wishlist>a{position:relative;}
		.wishlist-header .qty{position:absolute;top: -5px;right: -12px;min-width:20px;height:20px;
		line-height:20px;text-align:center;background:#4c6689;color:#fff;font-size:12px;
		border-radius: 50%;overflow: hidden;}
		.wishlist-header .qty>span{font-size:12px;}
		.wishlist-header .qty>i{display:none;}

		/*hide slick hover*/
		.slick-slider:hover .slick-prev, 
		.slick-slider:hover .slick-next{display:none!important;}
		/*hide non-sense links*/
		.nav-sections .header.links:nth-child(n+2) {display: none;}
		.nav-sections .header.links .qty>i{font-style:normal;}
		.vicomage-megamenu li.level0 .submenu .content-hot-category .block-cat .thumb .title_cat .content-cat{text-decoration:none;}
	}
</style>
<header class="page-header header-type<?php echo $header_type; ?>">
	<?php if($header_type == 1): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						   <i class="fa fa-phone" aria-hidden="true"></i><span>Contact us toll free: <a style="color:#fff;" href="mailto:sales@upettools.com" target="_blank">sales@upettools.com</a></span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $25</p>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="header-content-type">
			<div class="row">
				<div class="col-sm-4 col-md-4 col-lg-4 header-content-left">
					<div class="header-search">
						<div class="search-switcher">
							<div class="dropdown-toggle">
								<div class="icon-search"><i class="flaticon-search4"></i></div>
							</div>
							<div class="dropdown-switcher">
								<?php echo $this->getChildHtml("top.search"); ?>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4 header-center">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-4 header-right">
					<div class="header-content-right">
						<div class="header-content-bottom">
							<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); ?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links">
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Login') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('Register') ?></a> 
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="html: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content-menu">
			<div class="container">
				<div class="header-menu">
					<?php echo $this->getChildHtml("navigation.sections"); ?>
				</div>
			</div>
			<a id="fixedWholesale" href="/dropshipping-and-wholesale">Wholesale and Dropshipping</a>
		</div>
	</div>
	
	<?php endif; ?>
	
	<?php if($header_type == 2 ): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						  <i class="fa fa-phone" aria-hidden="true"></i><span>Call us toll free: (+100) 123 456 7890</span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $100</p>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
    <div class="header-content header-sticker sticker">
		<div class="container-none">
			<div class="row">
				<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-12 header-content-center">
					<div class="header-menu">
						<div class="container">
							<div class="header-menu-content">
								 <?php echo $this->getChildHtml("navigation.sections"); ?>
							</div>
						</div>
					</div>
					<div class="header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); ?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links">
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Login') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('Register') ?></a> 
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="header-search">
								<div class="search-switcher">
									<div class="dropdown-toggle">
										<div class="icon-search"><i class="flaticon-search2"></i></div>
									</div>
									<div class="dropdown-switcher">
										<?php echo $this->getChildHtml("top.search"); ?>
									</div>
								</div>
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if( $header_type == 3): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-7">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-5">
					<div class="header-search">
						<div class="search-switcher">
							<div class="dropdown-toggle">
								<div class="icon-search"><i class="flaticon-search2"></i></div>
							</div>
							<div class="dropdown-switcher">
								<?php echo $this->getChildHtml("top.search"); ?>
							</div>
						</div>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("minicart"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="container">
			<div class="header-content-bg">
				<div class="row">
					<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-12 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-menu">
									 <?php echo $this->getChildHtml("navigation.sections"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
	
	<?php if($header_type == 4): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="container">
			<div class="header-content-type">
				<div class="row">
					<div class="col-sm-3 col-md-4 col-lg-4 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-5 header-center">
						<div class="header-search">
							<div class="search-switcher">
								<div class="dropdown-toggle">
									<div class="icon-search"><i class="flaticon-search2"></i></div>
								</div>
								<div class="dropdown-switcher">
									<?php echo $this->getChildHtml("top.search"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
									<span data-bind="scope: 'wishlist'" class="link wishlist">
									<a href="<?php echo $this->getUrl('wishlist') ?>">
										<span class="flaticon-heart1"></span> 
										<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
									</a>
								</div>
								<script type="text/x-magento-init">
									{
										"*": {
											"Magento_Ui/js/core/app": {
												"components": {
													"wishlist": {
														"component": "Magento_Wishlist/js/view/wishlist"
													}
												}
											}
										}
									}

								</script>
								 <div class="header-top-right">
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content-menu ">
			<div class="container">
				<div class="header-menu">
					<?php echo $this->getChildHtml("navigation.sections"); ?>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
	<?php if($header_type == 5): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	 <div class="header-content header-sticker sticker">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 col-md-3 col-lg-3 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-12 header-content-center">
					<div class="header-menu">
						<div class="container">
							<div class="header-menu-content">
								 <?php echo $this->getChildHtml("navigation.sections"); ?>
							</div>
						</div>
					</div>
					<div class="header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-search">
									<div class="search-switcher">
										<div class="dropdown-toggle">
											<div class="icon-search"><i class="flaticon-search2"></i></div>
										</div>
										<div class="dropdown-switcher">
											<?php echo $this->getChildHtml("top.search"); ?>
										</div>
									</div>
								</div>
								<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
									<span data-bind="scope: 'wishlist'" class="link wishlist">
									<a href="<?php echo $this->getUrl('wishlist') ?>">
										<span class="flaticon-heart1"></span> 
										<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
									</a>
								</div>
								<script type="text/x-magento-init">
									{
										"*": {
											"Magento_Ui/js/core/app": {
												"components": {
													"wishlist": {
														"component": "Magento_Wishlist/js/view/wishlist"
													}
												}
											}
										}
									}

								</script>
								 <div class="header-top-right">
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 6): ?>
	<div class="header-content header-sticker sticker">
		<div class="container-none">
			<div class="header-content-type">
				<div class="row">
					<div class="col-sm-4 col-md-4 col-lg-4 header-content-left">
						<span id="btn-bar" class="icon-barmenu"><i class="flaticon-bars1"></i></span>
						<div class="header-search">
							<div class="search-switcher">
								<div class="dropdown-toggle">
									<div class="icon-search"><i class="flaticon-search2"></i></div>
								</div>
								<div class="dropdown-switcher">
									<?php echo $this->getChildHtml("top.search"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-4 header-center">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-4 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); ?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links">
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Login') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('Register') ?></a> 
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="siderbarmenu siderbar-menu">
		<div class="siderbarmenu-content">
			<a href="#" class="btn-close"><i class="flaticon-close1"></i></a>
			<div class="header-menu">
				<?php echo $this->getChildHtml("accordion.menu"); ?>
				<?php // echo $this->getChildHtml("navigation.sections"); ?>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 7): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						  <i class="fa fa-phone" aria-hidden="true"></i><span>Call us toll free: (+100) 123 456 7890</span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $100</p>
					</div>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
					<div class="top-links-header switcher" id="links-header">
						<div class="actions dropdown options links-header-options">
							<div class="action toggle links-header-trigger" id="links-header-trigger">
								<strong><i class="fa fa-user"></i><?php echo __('My Account') ?></strong>
							</div>
							<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
											"appendTo":".links-header-options",
											"triggerTarget":"#links-header-trigger",
											"closeOnMouseLeave": false,
											"triggerClass":"active",
											"parentClass":"active",
											"buttons":null}}'>
								<?php echo $this->getChildHtml("header.links"); ?>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content ">
		<div class="container">
			<div class="header-content-bg">
				<div class="row">
					<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-12 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-menu siderbar-menu">
									 <?php echo $this->getChildHtml("navigation.sections"); ?>
								</div>
								 <div class="header-top-right">
									
									<div class="header-search">
										<div class="search-switcher">
											<div class="dropdown-toggle">
												<div class="icon-search"><i class="flaticon-search2"></i></div>
											</div>
											<div class="dropdown-switcher">
												<?php echo $this->getChildHtml("top.search"); ?>
											</div>
										</div>
									</div>
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="header-social">
						<div class="container">
							<ul class="list-inline">
								<li><a href="#" class="social-link facebook"><i class="fa fa-facebook"><span class="hidden">facebook</span></i></a></li>
								<li><a href="#" class="social-link twitter"><i class="fa fa-twitter"><span class="hidden">twitter</span></i></a></li>
								<li><a href="#" class="social-link google-plus"><i class="fa fa-google-plus"><span class="hidden">google-plus</span></i></a></li>
								<li><a href="#" class="social-link pinterest"><i class="fa fa-pinterest"><span class="hidden">pinterest</span></i></a></li>
							</ul>				
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 8): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="header-content-type">
			<div class="header-content-left">
				<div class="header-search">
					<div class="search-switcher">
						<div class="dropdown-toggle">
							<div class="icon-search"><i class="flaticon-search2"></i></div>
						</div>
						<div class="dropdown-switcher">
							<?php echo $this->getChildHtml("top.search"); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="header-logo">
				 <?php echo $this->getChildHtml("logo_theme"); ?>
			</div>
			<div class="header-right">
				<div class="header-content-right">
					<div class="header-content-bottom">
						<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
							<span data-bind="scope: 'wishlist'" class="link wishlist">
							<a href="<?php echo $this->getUrl('wishlist') ?>">
								<span class="flaticon-heart1"></span> 
								<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
							</a>
						</div>
						<script type="text/x-magento-init">
							{
								"*": {
									"Magento_Ui/js/core/app": {
										"components": {
											"wishlist": {
												"component": "Magento_Wishlist/js/view/wishlist"
											}
										}
									}
								}
							}

						</script>
						 <div class="header-top-right">
							<?php echo $this->getChildHtml("minicart"); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="header-wrapper">
				<div class="header-menu">
					<div class="container">
					 <?php echo $this->getChildHtml("navigation.sections"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
</header>