<?php
    $header_type = $this->getConfig('vicomage_general_config/header/header_type');
?>
<!-- new add at header -->
<style type="text/css" media="all">
	/* --- common style --- */
	.toolbar select{padding-left: 10px;}
	.swatch-option{border: 1px solid rgba(0, 0, 0, 0.2);}
	.header-top .header-top-right,.page-header #switcher-currency .action.toggle:after{line-height:30px;}
	.links-header-dropdown .link.wishlist .qty>i{font-style:normal;}
	.minicart-wrapper .block-minicart{padding: 25px 10px;}
	.minicart-items-wrapper .minicart-items{padding: 0 10px;}
	.account .page-wrapper .column.main a{color: #4c6689;}
	.account .page-wrapper .column.main a:hover{color: #2a6ac1;text-decoration: underline;}
	#switcher-language a{color: #fff;font-size: 12px;text-shadow: 0 4px 4px rgba(0,0,0,0.6);padding: 2px 4px;
		border-radius: 5px;border-width: 3px;border-style: solid;
		border-color: #e66e2e #bb4508 #b1521e #b54a11;
		background: #c34807;
		background: -webkit-linear-gradient(to bottom,#e06422,#d6530d);
		background: linear-gradient(to bottom,#e06422,#d6530d);
		-webkit-transition: all 0.1s linear;
		transition: all 0.1s linear;}
	#switcher-language a.current{
		cursor:default;
		text-decoration: none;
	}
	#switcher-language a.lang:hover{
		text-decoration: none;
		text-shadow: 0 2px 4px rgba(0,0,0,0.6);
		border-color: #ea6f2d #d25b1d #ba4000 #b54a11;
		background: -webkit-linear-gradient(to bottom,#f1702b,#da5814);
		background: linear-gradient(to bottom,#f1702b,#da5814);
	}
	#switcher-language a.lang:active{
		text-decoration: none;
		text-shadow: 0 2px 4px rgba(0,0,0,0.6);
		border-color: #da5d1a #9c3d0c #b3490f #b54a11;
		background: -webkit-linear-gradient(to bottom,#bb531b,#ec8650);
		background: linear-gradient(to bottom,#bb531b,#ec8650);
	}
	#fixedWholesale{display:none;}
	.product-item-actions .actions-primary .stock.unavailable{
		padding: 0 15px;font-weight: 700;font-size: 12px;line-height: 30px;background:#ffffff;}
	.product-item-actions .actions-primary .stock.unavailable span{text-decoration: underline;}
	#backtotop{right: 12px;background-color: #0584bb;border-radius: 4px;}
	#backtotop:hover{background:#333333;}
	.minicart-items .item-qty{width:40px;padding:0;}
	@media all and (min-width: 769px), print {
		html.ie8,.ie8 body,html.ie9,.ie9 body,html.ie10,.ie10 body,html.ie11,.ie11 body{height:auto;}/*IE hack*/
		.header-content-menu{position: relative;}
		.header-content{margin-bottom: 40px;}
		.cms-home .header-content{margin-bottom: 0;}
		.searchsuite-autocomplete{left:0;}
		#vigomobile-slider{display: none;}
		#vigohome1-slide{display: block;}
		#fixedWholesale{display:block;position:absolute;right:0;top:10px;color:#fff;font-size:14px;
			text-shadow: 0 4px 4px rgba(0,0,0,0.6);
			padding: 2px 4px;border-radius: 5px;border-width: 3px;border-style: solid;
			border-color: #0584bb #03577b #094f6d #106286;
			background: #106286;
			background: -webkit-linear-gradient(to bottom,#0584bb,#4c6689);
			background: linear-gradient(to bottom,#0584bb,#4c6689);
			-webkit-transition: all 0.1s linear;
			transition: all 0.1s linear;
		}
		#fixedWholesale:hover{
			text-decoration: none;
			border-color: #006f9e #03577b #094f6d #106286;
			background: -webkit-linear-gradient(to bottom,#07506f,#577092);
			background: linear-gradient(to bottom,#07506f,#577092);
			
		}
		#fixedWholesale:active{
			text-decoration: none;
			border-color: #1496cc #03577b #0a5777 #106286;
			background: -webkit-linear-gradient(to bottom,#0f688e,#0f80af);
			background: linear-gradient(to bottom,#0f688e,#0f80af);
		}
		.header-container-fixed #fixedWholesale{display:none;}
		/*go quickly*/
		.header-goQuickly{}
		.header-goQuickly .quicklyBox{position: relative;margin: 0 0 0 -40px;}
		.header-goQuickly .quicklyContent{position: absolute;left: 0;top: 0;width: 100%;font-size:12px;
			border: solid 1px #ddd;border-top: none;background: rgba(247, 247, 247, .9);border-radius: 0 0 6px 6px;
			box-shadow: 0 1px 2px rgba(0,0,0,.15);overflow: hidden;}
		.quicklyContent .title{display: inline-block;vertical-align: middle;background: #d2d2d2;/*#eee;*/font-weight:bold;color: #444;padding: 9px 10px;}
		.quicklyContent .title .fa{display: inline-block;vertical-align: text-bottom;font-size: 16px;margin-left: 6px;color: #aaa; line-height: 1;}
		.quicklyContent .links{display: inline-block;vertical-align: middle;list-style: none;padding: 0;margin: 0;}
		.quicklyContent .links li{display: inline-block;margin: 0;vertical-align: middle;padding: 9px 10px;position: relative;}
		.quicklyContent .links li:not(:first-child):before{content: '';display: block;width: 1px;height: 16px;background-color: #b9b9b9;position: absolute;left: -1px;top: 50%;margin-top: -8px;}
		.quicklyContent .links li a{color:#666;}
		.quicklyContent .links li a:hover{color: #4c6689;text-decoration: underline;}
		.header-container-fixed .header-goQuickly .quicklyContent{background: #fff;box-shadow: 0 1px 2px rgba(0,0,0,.1);border-top: solid 1px rgba(221, 221, 221,.2);}
		#backtotop{bottom:40px;}
		.page.messages{text-align:center;}
		.message>*:first-child:before{
			margin:0!important;position:initial!important;
		}
		.block-customize .tabs{display:none;}
		.block-authentication.block-customize>.block-new-customer{-webkit-order:1;-ms-order:1;order:1;padding: 10px 0 0 40px;border-left: 1px solid #c1c1c1;}
		.block-authentication.block-customize>.block-new-customer::before{height: 36px;line-height: 34px;
			margin: -19px 0 0 -18px;min-width: 36px;background: #fff;border: 1px solid #c1c1c1;border-radius: 50%;
			box-sizing: border-box;color: #c1c1c1;content: attr(data-label);display: inline-block;
			letter-spacing: normal;padding: 0 .2rem;position: absolute;text-align: center;text-transform: uppercase;left: 50%;top: 50%;}
		.block-authentication.block-customize>.block[class]+.block-customer-login{-webkit-order:0;-ms-order:0;order:0;padding: 10px 30px 0 0;border-left:0;}
		.block-authentication.block-customize>.block[class]+.block-customer-login::before{display:none;}
		.block-authentication .actions-toolbar>.primary{float:left;}
		.block-authentication .actions-toolbar>.secondary{margin:0 0 0 2rem;}
		.account-list .fa{display: none;}
		/*section-hot-deal*/
		.section-prolist-feature .prolist-feature-middle{display: none;}
	}
	@media only screen and (min-width: 769px) and (max-width: 898px), print {
		.header-container-fixed #mainMenu>li:first-child{display: none;}
	}
	@media only screen and (max-width: 768px), print{
		/*header*/
		.page-header .switcher .options ul.dropdown{left: 0;}
		.page-header.header-type1 .header-right{z-index:51;}
		.page-header .header-content{border-bottom: 1px solid #E7E7E8;}
		.page-header .header-content-type{padding: 0 20px 50px 20px;}
		.page-header .header-logo .logo{margin:10px 0;}
		.page-header .header-logo .nav-toggle{left: -5px;}
		.page-header .header-logo .nav-toggle,
		.page-header.header-type1 .header-right{top: 12px;}
		.columns .column.main{padding-bottom:0;}
		.account-list a .fa{display: block;margin-bottom: 4px;font-size: 24px;color:#0584bb;}
		.account-list.notLogin,.account-list.hasLogin{display:flex;-webkit-box-pack: center;justify-content: center;}
		.account-list.notLogin a,.account-list.hasLogin a{margin: 0 15px;text-align: center;}
		.header-goQuickly{display: none;}
		/*switcher*/
		.nav-sections .switcher:before,
		.nav-sections .switcher:after{display: table;content: " ";}
		.nav-sections .switcher:after{clear: both;}
		#switcher-language-nav{display:none;}
		#switcher-language-nav,#switcher-currency-nav {padding: 14px 15px;border-bottom:1px solid #e2e5f1;box-shadow: 0 0 1px rgba(0,0,0,0.04);}
		#switcher-currency-nav .switcher-title{display:inline-block!important;font-weight: normal;color: #7e859b;font-size: 13px;}
		.page-header .switcher .options{float:right;text-align:right;}
		.switcher-trigger strong,.page-header .switcher .options ul.dropdown a{font-size:13px;padding: 0;}
		.page-header .switcher-currency.switcher .options.active{}
		#switcher-language-nav a{display:inline-block;font-weight:normal;}
		#switcher-language-nav a.lang{padding:5px 15px;display:none;}
		#switcher-language-nav a.lang::before {content: '\e608';font-family: 'luma-icons';-webkit-font-smoothing: antialiased;font-size: 8px;
			line-height: 20px;color: inherit;margin: 0;vertical-align: top;display: inline-block;font-weight: normal;overflow: hidden;speak: none;text-align: center;}
		#switcher-currency-nav ul.dropdown{box-shadow:none;background:none;border:none;min-width: initial;margin: 0;}
		#switcher-currency-nav .options.active ul.dropdown{position:initial;}
		.page-header .switcher .options ul.dropdown li:hover{background:none;}
		/*search*/
		.header-type1 .block-search .action.search{height:36px;left:initial!important;right:8px;}
		.page-header .block-search .action.search::before{line-height:36px;color:#999;}
		.searchsuite-autocomplete{left:0;width:100%;}
		.searchsuite-autocomplete ul li a{word-break:break-all;}
		.page-header .header-content-left{margin: 0 -20px;}
		.page-header .header-search{width: 100%;top: initial;bottom: 50px;left: 0;}
		.page-header .header-search .search-switcher .dropdown-toggle{display: none;}
		.page-header .header-search .search-switcher .dropdown-switcher{width: 100%;opacity: 1;margin-top: 0;visibility: visible;box-shadow:none;}
		.page-header .block-search input{padding: 0 30px 0 8px;height: 36px;line-height: 36px;color:#666666;background: rgb(104, 168, 224,.1);
			border:1px solid #b9deff;}
		.page-header .block-search input:focus{box-shadow: 0 0 3px 1px #68a8e0;}
		/*search right*/
		.page-header .wishlist-header{display: none;}
		.page-header .wishlist-header a{font-size:20px;}
		.page-header .wishlist-header .wishlist>a{position:relative;}
		.page-header .wishlist-header .wishlist>a .flaticon-heart1{font-size:20px;line-height:14px;}
		.wishlist-header .qty{position:absolute;top: -5px;right: -12px;min-width:20px;height:20px;
			line-height:20px;text-align:center;background:#4c6689;color:#fff;font-size:12px;
			border-radius: 50%;overflow: hidden;}
		.wishlist-header .qty>span{font-size:12px;}
		.wishlist-header .qty>i{display:none;}
		.minicart-wrapper{max-width:44px;}
		.modal-popup.modal-slide._inner-scroll._show{-webkit-overflow-scrolling:none;-webkit-overflow-scrolling:initial;}
		/*menu*/
		.vicomage-megamenu.navigation li.link-home,.vicomage-megamenu.navigation li.fullwidth,
		.vicomage-megamenu.navigation li.link-home+.dropdown>a.level-top,.vicomage-megamenu.navigation li.link-home+.dropdown>.open-children-toggle{display:none;}
		.vicomage-megamenu.navigation li.link-home+.dropdown>.submenu{display:block!important;padding:0;}
		.vicomage-megamenu.navigation .submenu li a{text-transform:capitalize;padding:14px 0;font-size:14px;font-family: 'Helvetica Neue';}
		.navigation .submenu > li{border-top: 1px solid #ddd;}
		.navigation .submenu > li:nth-child(1){border-top:none;}
		.vicomage-megamenu.navigation li.ui-menu-item>.open-children-toggle{height: 100%;}
		.navigation .parent>.level-top:after,
		.navigation .parent>.level-top.ui-state-active:after{content: '\e608';top: 16px;}
		.vicomage-megamenu.navigation .submenu{display:none!important;}
		.nav-sections .header.links a, .nav-sections .header.links a:hover{font-size: 12px;padding:8px 0;color: #5b5c5f;font-family: 'Helvetica Neue';}
		.nav-sections .header.links li:last-child>a{border-bottom:none;}
		.navigation .parent>.level-top:after{right:14px;}
		.prolist-feature-top .title-page{margin:10px 0;}
		.products-grid .product-item{margin-bottom:10px;}
		.product-item-details{padding:0 0 20px;}
		.product-item-name{margin:2px 0;}
		.product-item-name, .product.name a{font-size:12px;font-weight:normal;color: #404553;}
		.product-reviews-summary{margin:0;line-height:0;}
		.rating-summary .rating-result[title="0%"] {display: none;}
		.form-customer-create .actions-toolbar .secondary a.action ,
		.form-password-forget .actions-toolbar .secondary a.action{color: #fff;}
		.page-header .switcher .options .action.toggle:after{line-height:20px;}
		.product-label.sale-label{top: 30px;left: 8px;}
		.product-label.new-label{top: 5px;left: 8px;}
		#vigomobile-slider{display: block;}
		#vigohome1-slide{display: none;}
		.vicomage-slider .slick-slide[data-slick-index="0"] .text-slide .caption1{color: #c24343;text-shadow: -1px 0px 1px #fff, 2px -1px 2px rgba(0,0,0,.8);}
		.vicomage-slider .slick-active .slide-caption .caption1{font-family: Gabriola;font-style: italic;font-weight: 700;}
		.vicomage-slider .slick-active .slide-caption .caption2,
		.vicomage-slider .slick-active .slide-caption .caption3{text-transform: capitalize;font-size: 14px;font-weight: normal;}

		/*hide slick hover*/
		.slick-slider:hover .slick-prev, 
		.slick-slider:hover .slick-next{display:none!important;}
		/*hide non-sense links*/
		.nav-sections .header.links:nth-child(n+3) {display: none;}
		.nav-sections .header.links.notLogin+.header.links{display:none;}
		.nav-sections .header.links .qty>i{font-style:normal;}
		.vicomage-megamenu li.level0 .submenu .content-hot-category .block-cat .thumb .title_cat .content-cat{text-decoration:none;}
		.products-grid .product-item-info:hover .btn-quickview, .products-grid .product-item-info.active .btn-quickview{display:none;}
		.products-grid .product-item-info:hover .product-item-inner{visibility: hidden;opacity: 0;}
		.product-item-inner .product-item-actions .actions-primary .tocart{background:none;}
		/*checkout sign in*/
		.block-customize .tabs{margin:0;padding:0;}
		.block-customize .tabs li{list-style:none;display:inline-block;float:left;width:48%;margin:0;padding:10px 0;text-align:center;line-height:30px;color:#333333;
			background:#ffffff;border:1px solid #ccc;cursor:pointer;-webkit-transition: all 0.1s linear;transition: all 0.1s linear;}
		.block-customize .tabs li:nth-child(2){border-left:none;}
		.block-customize .tabs li.current{background: #4c6689;color: #fff;}
		.block-authentication.block-customize .block[class]+.block::before{display:none;}
		.block-authentication .tabs+.block[class]{margin-top: 10px;padding-top: 10px;border-top: 1px solid #c1c1c1;}
		.block-authentication.block-customize .block[class]+.block{margin-top:10px;padding-top:10px;}
		.block-customize .form .fieldset>.field{margin: 0 0 10px;}
		.block-customize .fieldset{margin: 0 0 20px;}
		.block-customize.block-authentication .actions-toolbar>.secondary{padding-top:0;}
		.block-customize.block-authentication .block-title strong{font-weight:500;text-transform:initial;}
		/*footer*/
		#backtotop{bottom:60px;right:14px;opacity:0.8;}
		.catalog-product-view #backtotop{bottom: 114px;}
		.zopim{position: fixed!important;top:initial!important;bottom:0!important;opacity:0.88;}
		.catalog-product-view>.zopim{bottom: 72px!important;}
		/*home page vigoproduct and category page*/
		.prolist-feature-top .vigoproduct,.prolist-feature-bottom .vigoproduct,.section-hot-deal .vigoproduct{}
		.prolist-feature-top .vigoproduct .title-page,
		.section-prolist.section-prolist-feature .prolist-feature-bottom .vigoproduct .title-page,
		.section-hot-deal .vigoproduct .title-page{display: block;margin: 0;padding: 0 8px;text-align: left;}
		.prolist-feature-top .vigoproduct .title-page .subtitle,
		.section-prolist.section-prolist-feature .prolist-feature-bottom .vigoproduct .title-page .subtitle,
		.section-hot-deal .vigoproduct .title-page .subtitle{font-size: 16px;font-family: 'Proxima Nova','Helvetica Neue',Arial,sans-serif;text-transform: capitalize;color:#404553;
			padding: 4px 10px 4px 2px;border-bottom: 2px solid #0584bb;}
		.vigoproduct .title-page .subtitle::before{display: none;}
		.vigoproduct .products-custom.products-grid,
		.vigoproduct .products-custom .products{margin: 0;}
		.prolist-feature-top .vigoproduct .products-custom .products{margin: 0;}
		.prolist-feature-top .vigoproduct .products-grid .products .product-item,
		.prolist-feature-bottom .products-grid .product-item,
		.section-hot-deal .deal-right .products .product-item{padding: 8px 8px 12px;}
		.prolist-feature-top .vigoproduct .products-grid .products .product-item .product-item-info,
		.prolist-feature-bottom .products-grid .product-item .product-item-info,
		.section-hot-deal .deal-right .products .product-item .product-item-info{padding: 8px 4px 12px;box-sizing: border-box;box-shadow: 0 0 1px rgba(0,0,0,0.2);}
		.prolist-feature-top .vigoproduct .products-grid .products .product-item .product-item-info .product-item-details,
		.prolist-feature-bottom .products-grid .product-item .product-item-info .product-item-details,
		.section-hot-deal .deal-right .products .product-item .product-item-info .product-item-details{padding: 0;}
		.section-hot-deal .deal-right{padding: 10px 15px 0;border-bottom: none;}
		.page-products .product-item-info{box-sizing: border-box;box-shadow: 0 0 1px rgba(0,0,0,0.2);padding: 8px 4px 12px;}
		.page-products .product-item-details{padding: 0;}
		.product-item .price-box .old-price .price{font-size: 14px;}
		/*search page*/
		.search.results .toolbar .toolbar-amount{position:static;}
		/*mobile nav*/
		.nav-sections .header.links strong{display: block;padding: .8rem 20px;border-bottom: 1px solid #d1d1d1;color:#4c6689;}
		/*account page*/
		body.account .page-main>.columns{display: flex;}
		body.account .page-main>.columns .sidebar-main{-ms-flex-order: 0;-webkit-order: 0;order:0;}
		.account .page.messages{margin: 10px 0;}
		.account-nav.block-collapsible-nav{position:static;margin-bottom:20px;}
		.account-nav.block-collapsible-nav .title{width:100%;height:auto;border:1px solid;border-color: #0584bb #03577b #094f6d #106286;
			color: #fff;background: #0584bb;
			background: -webkit-linear-gradient(to bottom,#0584bb,#4c6689);
			background: linear-gradient(to bottom,#0584bb,#4c6689);
			box-shadow:0 -2px 4px rgba(0,0,0,0.1),2px 0 1px rgba(0,0,0,0.1),0 2px 4px rgba(0,0,0,0.1),-2px 0 1px rgba(0,0,0,0.1);}
		.account-nav.block-collapsible-nav .item a{text-transform: capitalize;}
		.account .page-title-wrapper h1{margin:0;}
		/*category page*/
		.catalog-category-view .page-main .columns>.sidebar{display:none;}
		.breadcrumbs .item:not(:last-child):after{margin: 0 2px;}
		/*prolist-feature-middle*/
		.section-hot-deal .deal-left{display: none;}
		.section-prolist-feature .prolist-feature-middle{display: block;margin: 0 -15px 10px;border-bottom: 1px solid #ddd;}
		.prolist-feature-middle .deal-left{padding: 20px 0 20px;background-position: center center;background-repeat: no-repeat;background-size: cover;}
		.prolist-feature-middle .main-title{display: none;}
		.prolist-feature-middle .deal-left .super-title{display: inline-block;margin: 0 0 10px;padding: 4px;color: #b31414;border: 1px solid;
			font-family: Helvetica;font-size: 26px;box-shadow: 0 0 2px rgba(179,20,20,.8);
			text-shadow: -1px 0px 1px #fff, 2px -1px 2px rgba(0,0,0,.5);background: rgba(255,255,255,.85);}
		.prolist-feature-middle .deal-left .deal-left-content{text-align: right;padding: 0 20px 0 0;}
		.prolist-feature-middle .deal-left .btn-shop-now{position: static;padding: 2px 4px;text-transform: capitalize;font-style: italic;font-weight: 600;}
		.prolist-feature-middle .deal-left .deal_price{margin: 0 0 10px;}
		.prolist-feature-middle .deal-left .deal_price,.prolist-feature-middle .deal-left .deal_price span{display:block;}
		.prolist-feature-middle .deal-left .deal_price .price-box>span{display: inline-block;}
		.prolist-feature-middle .deal-left .old-price .price-label{display: none;}
		.prolist-feature-middle .deal-left .deal_price .price{position:static!important;}
		.prolist-feature-middle .deal-left .special-price .price-container .price{font-size: 20px;color: #333;}
		.prolist-feature-middle .deal-left .old-price .price-container .price{font-size:14px;font-weight: 500;text-decoration: line-through;}
		.prolist-feature-middle .deal-left .second{display: none;}
		.prolist-feature-middle .deal-left .cp-countdown{}
		.prolist-feature-middle .deal-left .cp-countdown>span{font-weight: 600;padding:2px 4px;border: 1px solid #333;}
		.prolist-feature-middle .deal-left .cp-countdown span>span{color: #808080;font-weight: 500;}
		.prolist-feature-middle .deal-left .cp-countdown>span:nth-child(1){border-radius: 5px 0 0 5px;}
		.prolist-feature-middle .deal-left .cp-countdown>span:nth-child(3){border-radius: 0 5px 5px 0;}
		.prolist-feature-middle .deal-left .shop_now_link{display: block;margin: 10px 0 0 0;}
		/*social-login*/
		.mfp-content{/*margin: 40px auto;*/}
		#social-login-popup .fieldset{margin: 0 0 5px;}
		.social-login-title h2{font-size: 20px;}
		.mfp-content .block .block-title{font-weight:600;}
		.social-login .form-customer-login .action.create,
		.social-login .form-customer-create .action.back
		{padding: 5px;font-family: 'Roboto', sans-serif;background: #4c6689;border-radius: 4px;}
		.social-login .block .block-title::before{display: none;}
		.social-login .form-customer-create .fieldset>.field>.label, 
		.social-login .form-customer-create .fieldset>.fields>.field>.label{text-transform: capitalize;}
		.social-login .form-customer-create .fieldset>.field,
		.social-login .form-customer-create .fieldset>.fields>.field{margin: 0 0 5px;}
		.social-login .form-customer-create .field.field-name-firstname,
		.social-login .form-customer-create .field.field-name-lastname,
		.social-login .form-customer-create .field.password,
		.social-login .form-customer-create .field.confirmation,
		.social-login .form-customer-create .field.captcha .input-text{display: inline-block;width: 46%;vertical-align: top;}
		.social-login .form-customer-create .field.field-name-lastname,
		.social-login .form-customer-create .field.confirmation{margin:0 0 0 7%;}
		.social-login .form-customer-create input{height: 30px;}
		.social-login .form-customer-create input[name=is_subscribed]{height: initial;}
		.social-login .form-customer-create input[name=is_subscribed]+label{vertical-align: text-bottom;}
		.form-customer-create #check_email_referee,
		.form-customer-create #update_email_referee,
		.form-customer-create .action.captcha-reload{padding: 4px 8px;}
	}
	@media only screen and (max-width: 480px), print{
		.page-header .header-logo .logo{margin:10px 0;}
		.page-header .header-logo .nav-toggle{left: -5px;}
		.page-header .header-logo .nav-toggle,
		.page-header.header-type1 .header-right{top:12px;}
	}
</style>
<header class="page-header header-type<?php echo $header_type; ?>">
	<?php if($header_type == 1): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						   <i class="fa fa-phone" aria-hidden="true"></i><span>Contact us toll free: <a style="color:#fff;" href="mailto:sales@upettools.com" target="_blank">sales@upettools.com</a></span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $25</p>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="header-content-type">
			<div class="row">
				<div class="col-sm-4 col-md-4 col-lg-4 header-content-left">
					<div class="header-search">
						<div class="search-switcher">
							<div class="dropdown-toggle">
								<div class="icon-search"><i class="flaticon-search4"></i></div>
							</div>
							<div class="dropdown-switcher">
								<?php echo $this->getChildHtml("top.search"); ?>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4 header-center">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-4 header-right">
					<div class="header-content-right">
						<div class="header-content-bottom">
							<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); 
									$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links notLogin">
										<a class="visible-xs home-link" href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"><i class="fa fa-home" aria-hidden="true"></i><?php echo __('Home') ?></a>
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><i class="fa fa-user" aria-hidden="true"></i><?php echo __('Sign In') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><i class="fa fa-sign-in" aria-hidden="true"></i><?php echo __('Sign Up') ?></a> 
										<a class="visible-xs cart-link" href="<?php echo $storeManager->getStore()->getBaseUrl().'checkout/cart/' ?>"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Cart</a>
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="html: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content-menu">
			<div class="container">
				<div class="header-menu">
					<?php echo $this->getChildHtml("navigation.sections"); ?>
				</div>
			</div>
			<a id="fixedWholesale" href="/dropshipping-and-wholesale">Wholesale and Dropshipping</a>
		</div>
		<div class="header-goQuickly">
			<div class="container">
				<div class="quicklyBox">
					<div class="quicklyContent">
						<div class="title">Go quickly to <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></div>
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('quickly-links')->toHtml();?>			
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
	
	<?php if($header_type == 2 ): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						  <i class="fa fa-phone" aria-hidden="true"></i><span>Call us toll free: (+100) 123 456 7890</span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $100</p>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
    <div class="header-content header-sticker sticker">
		<div class="container-none">
			<div class="row">
				<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-12 header-content-center">
					<div class="header-menu">
						<div class="container">
							<div class="header-menu-content">
								 <?php echo $this->getChildHtml("navigation.sections"); ?>
							</div>
						</div>
					</div>
					<div class="header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); ?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links">
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Login') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('Register') ?></a> 
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="header-search">
								<div class="search-switcher">
									<div class="dropdown-toggle">
										<div class="icon-search"><i class="flaticon-search2"></i></div>
									</div>
									<div class="dropdown-switcher">
										<?php echo $this->getChildHtml("top.search"); ?>
									</div>
								</div>
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if( $header_type == 3): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-7">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-5">
					<div class="header-search">
						<div class="search-switcher">
							<div class="dropdown-toggle">
								<div class="icon-search"><i class="flaticon-search2"></i></div>
							</div>
							<div class="dropdown-switcher">
								<?php echo $this->getChildHtml("top.search"); ?>
							</div>
						</div>
					</div>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("minicart"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="container">
			<div class="header-content-bg">
				<div class="row">
					<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-12 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-menu">
									 <?php echo $this->getChildHtml("navigation.sections"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
	
	<?php if($header_type == 4): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="container">
			<div class="header-content-type">
				<div class="row">
					<div class="col-sm-3 col-md-4 col-lg-4 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-5 header-center">
						<div class="header-search">
							<div class="search-switcher">
								<div class="dropdown-toggle">
									<div class="icon-search"><i class="flaticon-search2"></i></div>
								</div>
								<div class="dropdown-switcher">
									<?php echo $this->getChildHtml("top.search"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
									<span data-bind="scope: 'wishlist'" class="link wishlist">
									<a href="<?php echo $this->getUrl('wishlist') ?>">
										<span class="flaticon-heart1"></span> 
										<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
									</a>
								</div>
								<script type="text/x-magento-init">
									{
										"*": {
											"Magento_Ui/js/core/app": {
												"components": {
													"wishlist": {
														"component": "Magento_Wishlist/js/view/wishlist"
													}
												}
											}
										}
									}

								</script>
								 <div class="header-top-right">
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content-menu ">
			<div class="container">
				<div class="header-menu">
					<?php echo $this->getChildHtml("navigation.sections"); ?>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
	<?php if($header_type == 5): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	 <div class="header-content header-sticker sticker">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 col-md-3 col-lg-3 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-12 header-content-center">
					<div class="header-menu">
						<div class="container">
							<div class="header-menu-content">
								 <?php echo $this->getChildHtml("navigation.sections"); ?>
							</div>
						</div>
					</div>
					<div class="header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-search">
									<div class="search-switcher">
										<div class="dropdown-toggle">
											<div class="icon-search"><i class="flaticon-search2"></i></div>
										</div>
										<div class="dropdown-switcher">
											<?php echo $this->getChildHtml("top.search"); ?>
										</div>
									</div>
								</div>
								<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
									<span data-bind="scope: 'wishlist'" class="link wishlist">
									<a href="<?php echo $this->getUrl('wishlist') ?>">
										<span class="flaticon-heart1"></span> 
										<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
									</a>
								</div>
								<script type="text/x-magento-init">
									{
										"*": {
											"Magento_Ui/js/core/app": {
												"components": {
													"wishlist": {
														"component": "Magento_Wishlist/js/view/wishlist"
													}
												}
											}
										}
									}

								</script>
								 <div class="header-top-right">
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 6): ?>
	<div class="header-content header-sticker sticker">
		<div class="container-none">
			<div class="header-content-type">
				<div class="row">
					<div class="col-sm-4 col-md-4 col-lg-4 header-content-left">
						<span id="btn-bar" class="icon-barmenu"><i class="flaticon-bars1"></i></span>
						<div class="header-search">
							<div class="search-switcher">
								<div class="dropdown-toggle">
									<div class="icon-search"><i class="flaticon-search2"></i></div>
								</div>
								<div class="dropdown-switcher">
									<?php echo $this->getChildHtml("top.search"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-4 header-center">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-4 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="top-links-header switcher" id="links-header">
								<?php

									$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
									$isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH); ?>
								<?php if($isLoggedIn){ ?>
									<div class="actions dropdown options links-header-options">
										<div class="action toggle links-header-trigger" id="links-header-trigger">
										<strong class="" data-bind="scope: 'customer'">
											<span data-bind="text: customer().fullname ? $t('Welcome,%1').replace('%1', customer().firstname) : ''"></span>
										</strong>
										<script type="text/x-magento-init">
										{
											"*": {
												"Magento_Ui/js/core/app": {
													"components": {
														"customer": {
															"component": "Magento_Customer/js/view/customer"
														}
													}
												}
											}
										}
										</script>
										</div>
										<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
														"appendTo":".links-header-options",
														"triggerTarget":"#links-header-trigger",
														"closeOnMouseLeave": false,
														"triggerClass":"active",
														"parentClass":"active",
														"buttons":null}}'>
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								<?php } else { ?>
									<div class="account-list header links">
										<a class="login-link" href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Login') ?></a><span class="line-padding">/</span>
										<a class="register-link" href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('Register') ?></a> 
									</div>
								<?php } ?>
								
								
								
							</div>
							<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
								<span data-bind="scope: 'wishlist'" class="link wishlist">
								<a href="<?php echo $this->getUrl('wishlist') ?>">
									<span class="flaticon-heart1"></span> 
									<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
								</a>
							</div>
							<script type="text/x-magento-init">
								{
									"*": {
										"Magento_Ui/js/core/app": {
											"components": {
												"wishlist": {
													"component": "Magento_Wishlist/js/view/wishlist"
												}
											}
										}
									}
								}

							</script>
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="siderbarmenu siderbar-menu">
		<div class="siderbarmenu-content">
			<a href="#" class="btn-close"><i class="flaticon-close1"></i></a>
			<div class="header-menu">
				<?php echo $this->getChildHtml("accordion.menu"); ?>
				<?php // echo $this->getChildHtml("navigation.sections"); ?>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 7): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-4">
					<div class="header-custom-block">
						  <i class="fa fa-phone" aria-hidden="true"></i><span>Call us toll free: (+100) 123 456 7890</span>
					</div>
				</div>
				<div class="header-top-right col-sm-8">
					<div class="header-text-shipping switcher">
						<p>Free worldwide shipping - On order over $100</p>
					</div>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
					<div class="top-links-header switcher" id="links-header">
						<div class="actions dropdown options links-header-options">
							<div class="action toggle links-header-trigger" id="links-header-trigger">
								<strong><i class="fa fa-user"></i><?php echo __('My Account') ?></strong>
							</div>
							<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
											"appendTo":".links-header-options",
											"triggerTarget":"#links-header-trigger",
											"closeOnMouseLeave": false,
											"triggerClass":"active",
											"parentClass":"active",
											"buttons":null}}'>
								<?php echo $this->getChildHtml("header.links"); ?>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content ">
		<div class="container">
			<div class="header-content-bg">
				<div class="row">
					<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
						<div class="header-logo">
							 <?php echo $this->getChildHtml("logo_theme"); ?>
						</div>
					</div>
					<div class="col-sm-12 header-right">
						<div class="header-content-right">
							<div class="header-content-bottom">
								<div class="header-menu siderbar-menu">
									 <?php echo $this->getChildHtml("navigation.sections"); ?>
								</div>
								 <div class="header-top-right">
									
									<div class="header-search">
										<div class="search-switcher">
											<div class="dropdown-toggle">
												<div class="icon-search"><i class="flaticon-search2"></i></div>
											</div>
											<div class="dropdown-switcher">
												<?php echo $this->getChildHtml("top.search"); ?>
											</div>
										</div>
									</div>
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>
							</div>
						</div>
					</div>
					<div class="header-social">
						<div class="container">
							<ul class="list-inline">
								<li><a href="#" class="social-link facebook"><i class="fa fa-facebook"><span class="hidden">facebook</span></i></a></li>
								<li><a href="#" class="social-link twitter"><i class="fa fa-twitter"><span class="hidden">twitter</span></i></a></li>
								<li><a href="#" class="social-link google-plus"><i class="fa fa-google-plus"><span class="hidden">google-plus</span></i></a></li>
								<li><a href="#" class="social-link pinterest"><i class="fa fa-pinterest"><span class="hidden">pinterest</span></i></a></li>
							</ul>				
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 8): ?>
	<div class="panel wrapper">
        <div class="panel header header-top">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-8">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="header-top-right col-sm-4">
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>
            </div>
        </div>
    </div>
	<div class="header-content header-sticker sticker">
		<div class="header-content-type">
			<div class="header-content-left">
				<div class="header-search">
					<div class="search-switcher">
						<div class="dropdown-toggle">
							<div class="icon-search"><i class="flaticon-search2"></i></div>
						</div>
						<div class="dropdown-switcher">
							<?php echo $this->getChildHtml("top.search"); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="header-logo">
				 <?php echo $this->getChildHtml("logo_theme"); ?>
			</div>
			<div class="header-right">
				<div class="header-content-right">
					<div class="header-content-bottom">
						<div class="wishlist-header link wishlist" data-bind="scope: 'wishlist'">
							<span data-bind="scope: 'wishlist'" class="link wishlist">
							<a href="<?php echo $this->getUrl('wishlist') ?>">
								<span class="flaticon-heart1"></span> 
								<!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
							</a>
						</div>
						<script type="text/x-magento-init">
							{
								"*": {
									"Magento_Ui/js/core/app": {
										"components": {
											"wishlist": {
												"component": "Magento_Wishlist/js/view/wishlist"
											}
										}
									}
								}
							}

						</script>
						 <div class="header-top-right">
							<?php echo $this->getChildHtml("minicart"); ?>
						</div>
					</div>
				</div>
			</div>
			<div class="header-wrapper">
				<div class="header-menu">
					<div class="container">
					 <?php echo $this->getChildHtml("navigation.sections"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
</header>
