<?php
    $thumbwidth = $block->getImageAttribute('product_page_image_small', 'width');
    $thumbheight = $block->getImageAttribute('product_page_image_small', 'height');         
?>
<?php
    $images = $block->getGalleryImagesJson();
    //print_r($images);exit;
    $imagesData = json_decode($images,true);
    $mainImage = '';
    $mainMainImageTitle = '';
    $mainThumbHtml = '';
    $mainThumbHtmlcount = 0;
    if(count($imagesData)>0){
        foreach($imagesData as $key=>$value){
            if(isset($value['isMain']) && $value['isMain'] == 1){
                $mainImage = $value['img'];
                $mainThumb = $value['thumb'];
                $mainFull = $value['full'];
                $mainMainImageTitle = $value['caption'];

                $mainThumbHtml.='<div class="fotorama__nav__frame fotorama__nav__frame--thumb fotorama__active" tabindex="0" role="button" data-gallery-role="nav-frame" data-nav-type="thumb" aria-label="" style="width: '.$thumbwidth.'px;" data-active="true" fast-image="yes" id="fast-main-'.$mainThumbHtmlcount.'">
                    <div class="fotorama__thumb fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" id="fast-loder-'.$mainThumbHtmlcount.'"><img src="'.$value['thumb'].'" alt="'.$value['caption'].'" class="fotorama__img" aria-hidden="false">
                    </div>
                </div>';
                $mainThumbHtmlcount++;
            }else{
                $mainThumbHtml.='<div class="fotorama__nav__frame fotorama__nav__frame--thumb" tabindex="0" role="button" data-gallery-role="nav-frame" data-nav-type="thumb" aria-label="" style="width: '.$thumbwidth.'px;" fast-image="yes" id="fast-main-'.$mainThumbHtmlcount.'">
                    <div class="fotorama__thumb fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" id="fast-loder-'.$mainThumbHtmlcount.'"><img src="'.$value['thumb'].'" alt="'.$value['caption'].'" class="fotorama__img" aria-hidden="false">
                    </div>
                </div>';
                $mainThumbHtmlcount++;
            }
        }
    }
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>
<style>
#mainSlicker{position:relative;}
.slick-left{display:none;}
.slick-main{height:100%;}
.slick-main .slick-dots li button{border:1px solid #ccc;}
.slick-main .slick-list{height:100%!important;}
.slick-main .slick-slide img{margin: 0 auto;}
.slick-loading{height:100%;}
.slick-loading>img{position:absolute;top:50%;right:50%;margin:-32px -32px 0 0;}
@media all and (min-width:769px),print{
    .slick-left{position:absolute;overflow:hidden;left:0;top:0;
        width:<?php echo $thumbwidth.'px';?>;
        max-height:<?php $thumbheight *=6; echo $thumbheight.'px';?>;}
    .slick-main{/*margin-left:<?php echo $thumbwidth.'px';?>;*/}
}
</style>

<div id="mainSlicker">
<div class="slick-main"></div>
<div class="slick-left"></div>
<div class="slick-loading"><img src="/pub/media/customize/loader-1.gif"/></div>
</div>

<script>
    require([
        'jquery',
        'slick'
    ],function($){
        //init show image
        var initData = <?php echo $images;?>;
        getSliderDom(initData,'init');
        
        $('#mainSlicker').css({'height':$('#mainSlicker').width()});
        $('.product-options-wrapper').delegate('.swatch-option','click',function(){
            $(this).addClass('selected').siblings().removeClass('selected');//selected
            var attribute_set = $('.swatch-opt .swatch-attribute');
            var select_obj = {};
            var attributes = {};
            select_obj.product_id = $('.product-info-price .price-final_price').attr('data-product-id');
            for(var j=0; j < attribute_set.length;j++){
                var key = attribute_set.eq(j).attr('attribute-code');
                attributes[key] = attribute_set.eq(j).find('.selected').attr('option-id');
            }
            select_obj.attributes = attributes;
            select_obj.isAjax = true;
            currentTest(select_obj);
            ajaxImage(select_obj);
    
        });
        function getSliderDom(data,method){
            var data = data;
            var thumbHtml = '';
            var normalHtml = '';
            if(method == 'init' && data.length > 0){
                for(var i=0; i< data.length; i++){
                    thumbHtml +='<div class="item"><img src="'+data[i].thumb+'" alt=""/></div>';
                    normalHtml +='<div class="item"><img src="'+data[i].img+'" alt=""/></div>';
                }
                currentTest("First init.");
            }else if(method == 'ajax'){
                for(var key in data){
                    currentTest(data[key]);
                    thumbHtml +='<div class="item"><img src="'+data[key].small+'" alt=""/></div>';
                    normalHtml +='<div class="item"><img src="'+data[key].medium+'" alt=""/></div>';
                }
                currentTest('Selected');
                currentTest(normalHtml);
            }
            $('.slick-main').html('<div>'+normalHtml+'</div>');
            //$('.slick-left').html('<div>'+thumbHtml+'</div>');
            resetSlideDom();
        }
        function resetSlideDom(){
            $('.slick-loading').hide();
            $('.slick-main>div,.slick-left>div').slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 1,
                adaptiveHeight: true
             });
        }
        function ajaxImage(select_data){
            if($.ajax()){
                $.ajax({
                    type:'post',
                    async:true,
                    url:'<?php echo $storeManager->getStore()->getBaseUrl().'swatches/ajax/media/';?>',
                    data:select_data,
                    dataType:'json',
                    beforeSend:function(){
                        $('.slick-loading').show();
                    },
                    complete:function(){},
                    success:function(data){
                        var tmpData = data.gallery;
                        if(tmpData){
                           getSliderDom(tmpData,'ajax');
                        }
                    }
                });
            }
        }
        function currentTest(l){
            if(false){
                window.console.log(l);
            }
        }
    });
</script>
