<?php
    $vico_helper = $this->helper('Vicomage\General\Helper\Data');
    $product_view = $vico_helper->getConfig('vicomage_general_config/product');
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
   if( $product_view['prev_next'] ){
        $_product = $block->getProduct();
        $prev_product = $vico_helper->getPrevProduct($_product);
        $next_product = $vico_helper->getNextProduct($_product);
?>
<?php if($prev_product || $next_product):?>
<div class="prev-next-products">
    <div class="title-page">
        <h2 class="subtitle">Viewed Products</h2>
    </div>
    <?php if($prev_product): ?>
    <?php
        $productImage = $_imagehelper->init($prev_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
        $productImageUrl = $productImage->getUrl();
    ?>
    <div class="product-nav product-prev">
        <div class="product-pop theme-border-color">
            <a href="<?php echo $prev_product->getProductUrl(); ?>" title="<?php echo $prev_product->getName(); ?>">
                <img class="product-image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                <h3 class="product-name">
                    <?php if(strlen($prev_product->getName())>27): ?>
                        <?php echo substr($prev_product->getName(),0,27).'...'; ?>
                    <?php else: ?>
                        <?php echo $prev_product->getName(); ?>
                    <?php endif; ?>
                </h3>
            </a>
        </div>
    </div>
    <?php endif; ?>
    <?php if($next_product): ?>
    <?php
        $productImage = $_imagehelper->init($next_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
        $productImageUrl = $productImage->getUrl();
    ?>
    <div class="product-nav product-next">
        <div class="product-pop theme-border-color">
            <a href="<?php echo $next_product->getProductUrl(); ?>" title="<?php echo $next_product->getName(); ?>">
                <img class="product-image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                <h3 class="product-name">
                    <?php if(strlen($next_product->getName())>27): ?>
                        <?php echo substr($next_product->getName(),0,27).'...'; ?>
                    <?php else: ?>
                        <?php echo $next_product->getName(); ?>
                    <?php endif; ?>
                </h3>
            </a>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
<?php
    }
?>