<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong style="display:none;" class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <a class="current" href="#" title="Current Store"><?php echo $block->escapeHtml($block->getStoreName()) ?></a>
    <?php foreach ($block->getStores() as $_lang): ?>
        <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
            <a class="lang" href="javascript:void(0);" title="Go to <?php echo $block->escapeHtml($_lang->getName()) ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'><?php echo $block->escapeHtml($_lang->getName()) ?></a>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
