<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<!-- new add at product view -->
<style type="text/css" media="all">
	@media only screen and (min-width: 769px) {
		.product-info-main .page-title-wrapper h1 {
			font-size: 24px;
		}
	}
</style>
<?php
	$vico_helper = $this->helper('Vicomage\General\Helper\Data');
	$product_config = $vico_helper->getConfig('vicomage_general_config/product');	
	$detailStyle = $product_config['detail_style'];
	
	if($detailStyle == '1column'){
		include (dirname(__FILE__).'/detail-style/detail-1.phtml');
	}  else {
		include (dirname(__FILE__).'/detail-style/detail-sidebar.phtml');
	}
?>

